rockmelonqa/rockmelonqa-ide

- common/src/codegen/playwright-charp/readme.md
- common/src/codegen/playwright-charp/reame.md
- common/src/codegen/playwright-csharp-mstest/templates/RunSettings.hbs
- common/src/codegen/playwright-csharp-nunit/templates/RunSettings.hbs
- electron/worker/actions/runTest.ts
- electron/worker/actions/runTest/commandBuilder.ts
- electron/worker/actions/runTest/runDotnetTestCommandBuilder.ts
- electron/worker/actions/runTest/runMsTestCommandBuilder.ts
- electron/worker/actions/runTest/runNunitCommandBuilder.ts
> Fix #3 tests are run in chromium when either the firefox or webkit browsers are selected

- common/src/codegen/utils/action-generator-dotnet/verifyAttribute.ts
- common/src/codegen/utils/action-generator-dotnet/verifyTitle.ts
- common/src/codegen/utils/action-generator-dotnet/verifyUrl.ts
> Fix #16 "Expect" in actions

- common/src/codegen/utils/action-generator-dotnet/inputByCode.ts
> Fix #20 Fix action Input By Code

- common/src/codegen/utils/action-generator-dotnet/verifyIsVisible.ts
- common/src/codegen/utils/action-registry-dotnet.ts
- common/src/file-defs/actionType.ts
- svelte/src/lib/context/IStringRes.ts
- svelte/src/lib/context/StringResEn.ts
> Fix  #17 Add action `verifyIsVisible`

- svelte/src/lib/dialogs/RunTestDialog/RunTestDialog.svelte
> Issue 55: Update method name getOutputProjectMetadata()

- common/src/codegen/utils/locator-generator-dotnet/relative.ts
> Fix #60 Issue with "Find By Relative" usage and that it causes codegen to fail

- .prettierignore
- common/src/codegen/playwright-csharp-mstest/templates/LocatorHelper.hbs
- common/src/codegen/playwright-csharp-nunit/templates/LocatorHelper.hbs
- common/src/codegen/playwright-csharp-xunit/templates/LocatorHelper.hbs
- common/src/codegen/playwright-typescript-jest/action-generator/verify.ts
- common/src/codegen/playwright-typescript-jest/action-registry.ts
- common/src/codegen/playwright-typescript-jest/templates/CustomMatcher.hbs
- common/src/codegen/playwright-typescript-jest/templates/LocatorHelper.hbs
- common/src/codegen/utils/action-generator-dotnet/verify.ts
- common/src/codegen/utils/action-generator-dotnet/verifyIsEditable.ts
- common/src/codegen/utils/action-generator-dotnet/verifyIsReadOnly.ts
- common/src/codegen/utils/action-registry-dotnet.ts
- common/src/file-defs/actionType.ts
- common/tests/codegen-tests/readme.md
- common/tests/test-helpers/common-files-dotnet.ts
- svelte/src/lib/context/IStringRes.ts
- svelte/src/lib/context/StringResEn.ts
> Fix #81 add verify is read only and verify is editable actions and remove the verify action

- .prettierignore
- common/src/codegen/playwright-csharp-mstest/templates/Locator.hbs
- common/src/codegen/playwright-csharp-nunit/templates/Locator.hbs
- common/src/codegen/playwright-csharp-xunit/playwrightCsharpXUnitTemplatesProvider.ts
- common/src/codegen/playwright-csharp-xunit/templates/Locator.hbs
- common/src/codegen/utils/locator-generator-dotnet/code.ts
- svelte/package-lock.json
> Fix #61 issue with find by code usage and that it causes codegen to fail

- common/src/codegen/playwright-csharp-mstest/playwrightCsharpMsTestCodeGen.ts
- common/src/codegen/playwright-csharp-mstest/templates/RmSingleCaseSuiteBase.hbs
- common/src/codegen/utils/locator-generator-dotnet/iframeName.ts
> Fix #58 setting find by i frame name to locate a page element causes codegen to fail

- common/src/codegen/playwright-csharp-xunit/templates/BaseClasses.hbs
- common/src/codegen/utils/locator-generator-dotnet/iframeId.ts
> Fix #19: Fix Xunit Iframe locator

- common/src/codegen/utils/locator-generator-dotnet/attribute.ts
> Remove redundant semicolon

- svelte/src/lib/context/StringResEn.ts
Hi @quockhanh ,
Please help me review this PR
> #56 Change the "Delete Test Case" dialog message

- common/src/index.ts
- electron/IPC/application.ts
- electron/applicationMenu.ts
- svelte/package-lock.json
- svelte/src/lib/components/Application.svelte
- svelte/src/lib/components/Application.ts
- svelte/src/lib/components/FileExplorer/Node.svelte
- svelte/src/lib/components/Tab/Tabs.svelte
- svelte/src/lib/context/AppContext.ts
- svelte/src/lib/dialogs/DeleteTestCaseConfirmationDialog.svelte
- svelte/src/lib/dialogs/NewProjectDialog.svelte
- svelte/src/lib/ipc/application.ts
- svelte/src/routes/get-started/+page.svelte
Issue 24 - Close Project menu item
> Issue 24 - Close Project menu item

- common/src/codegen/codegen.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/clear.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/click.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/clickPopup.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/closePopup.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/delay.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/gotoUrl.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/input.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/inputByCode.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/run.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/runCode.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/selectOption.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/verifyAttribute.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/verifyHasText.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/verifyHasValue.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/verifyIsEditable.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/verifyIsHidden.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/verifyIsReadOnly.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/verifyIsVisible.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/verifyTitle.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/verifyTitleContains.ts
- common/src/codegen/playwright-charp-common/action-generator-dotnet/verifyUrl.ts
- common/src/codegen/playwright-csharp-mstest/msTestProjMeta.ts
- common/src/codegen/playwright-csharp-nunit/nunitProjectMeta.ts
- common/src/codegen/playwright-csharp-xunit/xunitProjectMeta.ts
- svelte/src/lib/dialogs/CodeGenerationDialog.svelte
- svelte/src/lib/ipc/codeGenerator.ts
> Fix Issue 7 code gen check for unique object names when generating code 2

- common/src/codegen/playwright-charp-common/generateDatasetInfos.ts
- common/src/codegen/utils/stringUtils.ts
> Issue 138 cannot generate code with attached routine

- common/src/codegen/playwright-charp-common/action-generator-dotnet/closePopup.ts
- common/tests/codegen-tests/playwright-csharp-nunit/playwright-csharp-nunit.test.ts
- common/tests/codegen-tests/playwright-csharp-xunit/playwright-csharp-xunit.test-data.ts
- common/tests/codegen-tests/playwright-csharp-xunit/playwright-csharp-xunit.test.ts
- common/tests/codegen-tests/playwright-csharp/simple-routine.test-data.ts
> Issue 29: Fix Minor code formatting issue with the "Close Popup" action

- common/src/codegen/playwright-typescript/playwrightTypescriptCodeGen.ts
- common/src/codegen/playwright-typescript/templateProvider.ts
- common/src/codegen/playwright-typescript/templates/test-case-file.hbs
- package-lock.json
- svelte/package-lock.json
> Issue 181 typescritpt test routine does not work

- README.md
- common/src/codegen/playwright-typescript/templates/playwright-config.hbs
- electron/IPC/testRunner.ts
- electron/worker/actions/runTest.ts
- electron/worker/actions/runTest/runPlaywrightCommandBuilder.ts
- package-lock.json
- package.json
- svelte/src/lib/ipc/testRunner.ts
> Issue 182 typescript save test result to view later and hide run test box

- common/src/codegen/codegen-common/action-validator-registry.ts
- common/src/codegen/codegen-common/action-validators/clear.ts
- common/src/codegen/codegen-common/action-validators/click.ts
- common/src/codegen/codegen-common/action-validators/clickPopup.ts
- common/src/codegen/codegen-common/action-validators/closePopup.ts
- common/src/codegen/codegen-common/action-validators/delay.ts
- common/src/codegen/codegen-common/action-validators/gotoUrl.ts
- common/src/codegen/codegen-common/action-validators/input.ts
- common/src/codegen/codegen-common/action-validators/inputByCode.ts
- common/src/codegen/codegen-common/action-validators/run.ts
- common/src/codegen/codegen-common/action-validators/runCode.ts
- common/src/codegen/codegen-common/action-validators/runTestRoutine.ts
- common/src/codegen/codegen-common/action-validators/selectOption.ts
- common/src/codegen/codegen-common/action-validators/verifyAttribute.ts
- common/src/codegen/codegen-common/action-validators/verifyHasText.ts
- common/src/codegen/codegen-common/action-validators/verifyHasValue.ts
- common/src/codegen/codegen-common/action-validators/verifyIsEditable.ts
- common/src/codegen/codegen-common/action-validators/verifyIsHidden.ts
- common/src/codegen/codegen-common/action-validators/verifyIsReadOnly.ts
- common/src/codegen/codegen-common/action-validators/verifyIsVisible.ts
- common/src/codegen/codegen-common/action-validators/verifyTitle.ts
- common/src/codegen/codegen-common/action-validators/verifyTitleContains.ts
- common/src/codegen/codegen-common/action-validators/verifyUrl.ts
- common/src/codegen/codegenSourceProjectValidator.ts
- common/src/file-defs/shared.ts
> Issue 148 manage missing mandatory fields (3)

- common/src/codegen/playwright-charp-common/createOutputFileInfo.ts
- common/src/codegen/playwright-charp-common/dotnetTestProjectMetaGenerator.ts
- common/src/codegen/playwright-charp-common/playwrightCsharpCodeGen.ts
- common/src/codegen/playwright-charp-common/playwrightCsharpTemplatesProvider.ts
- common/src/codegen/playwright-csharp-mstest/playwrightCsharpMsTestCodeGen.ts
- common/src/codegen/playwright-csharp-mstest/playwrightCsharpMsTestTemplatesProvider.ts
- common/src/codegen/playwright-csharp-mstest/templates/TestCaseFile.hbs
- common/src/codegen/playwright-csharp-mstest/templates/TestRoutineFile.hbs
- common/src/codegen/playwright-csharp-nunit/playwrightCsharpNunitCodeGen.ts
- common/src/codegen/playwright-csharp-nunit/playwrightCsharpNunitTemplatesProvider.ts
- common/src/codegen/playwright-csharp-nunit/templates/TestCaseFile.hbs
- common/src/codegen/playwright-csharp-xunit/playwrightCsharpXUnitCodeGen.ts
- common/src/codegen/playwright-csharp-xunit/playwrightCsharpXUnitTemplatesProvider.ts
- common/src/codegen/playwright-csharp-xunit/templates/TestCaseFile.hbs
- common/src/codegen/playwright-typescript/playwrightTypeScriptMetaGenerator.ts
- common/src/codegen/types.ts
- common/src/codegen/utils/createName.ts
- common/tests/codegen-tests/playwright-csharp-mstest/playwright-csharp-mstest.test.ts
- common/tests/codegen-tests/playwright-csharp-nunit/playwright-csharp-nunit.test-data.ts
- common/tests/codegen-tests/playwright-csharp/project-meta.test.ts
- common/tests/codegen-tests/playwright-typescript/playwright-typescript-kitchen-sink.test-data.ts
> Issue 198 can t find test routine in test case

- electron/IPC/codeGenerator.ts
> Issue 198 can t find test routine in test case (2)

- common/src/codegen/playwright-typescript/playwrightTypescriptCodeGen.ts
- electron/IPC/testRunner/afterRunHandlerDotnet.ts
- package-lock.json
- svelte/package-lock.json
- svelte/src/lib/components/Editors/PhotoViewer.svelte
- svelte/src/lib/components/Editors/VideoViewer.svelte
> Fix video screenshot errors
